### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by marcode95**
Responsive Design and CSS Frameworks - Part 2

-focus on bootstrap
-used pre-defined grid and flex systems of bootstrap
-worked alone on this one due to taking a three week long sick-leave before

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello @marcode95 :wave: 

### I must say that your project was very pleasant to review, this is one of the hardest ones and you nailed it with expertise and professionalism :smile: 

qualitywork

### The only thing we need to change is this:

- [ ] You have some repeated CSS rules in your file, let's give them a class and make your code even dryer! Check below:

       9 |   text-decoration: none;
       8 |   color: black;
       6 |   font-family: "Roboto Condensed", serif;
       6 |   font-family: Arial, Helvetica, sans-serif;

## Summary

- Your README, PR description, and commit messages are very professional, keep up the good work :rocket: 
- Your code is the definition of DRY, awesome HTML, and CSS best practices :+1: 
- You used Bootstrap efficiently everywhere, your page's responsiveness is great :smile: 
- We can always get better, that's why I just pointed a minor issue to improve your project even more :100: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by marcode95** [comment]
Hey there!
Thanks for reviewing my code. About the issue: I was aware of those repeated classes, but chose not to change them to summarized classes because almost all of them refer to sometimes more than 10 html elements, which means I would actually have to write more code, which would be less clear to a colleague

**Comment by MuriloRoque** [comment]
Hello :wave: 
You are actually right, thank you for pointing that out!
This project is approved by me, please request for another review to make it official :pray:

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

### Hello again @marcode95 :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
